// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroCivilAPI.Models;

#nullable disable

namespace RegistroCivilAPI.Migrations
{
    [DbContext(typeof(RegistroCivilCitasContext))]
    [Migration("20260813174429_ConcurrenciaCitas")]
    partial class ConcurrenciaCitas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistroCivilAPI.Models.AvisoGlobal", b =>
                {
                    b.Property<int>("IdAviso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_aviso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAviso"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("titulo");

                    b.HasKey("IdAviso")
                        .HasName("PK_AvisosGlobales");

                    b.ToTable("Avisos_Globales", (string)null);
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.BitacoraAuditorium", b =>
                {
                    b.Property<int>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_bitacora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBitacora"));

                    b.Property<string>("AccionRealizada")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("accion_realizada");

                    b.Property<DateTime?>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_cambio")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdUsuarioInterno")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_interno");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("registro_id");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tabla_afectada");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("IdBitacora")
                        .HasName("PK__Bitacora__7E4268B0D2EB1BA4");

                    b.HasIndex("IdUsuarioInterno");

                    b.ToTable("Bitacora_Auditoria", (string)null);
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.CategoriasTramite", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__CD54BC5ADDE5FCC4");

                    b.ToTable("Categorias_Tramites", (string)null);
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.Cita", b =>
                {
                    b.Property<string>("IdCita")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("id_cita");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_hora_fin");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_hora_inicio");

                    b.Property<int>("IdCiudadano")
                        .HasColumnType("int")
                        .HasColumnName("id_ciudadano");

                    b.Property<int>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    b.Property<int>("IdTramite")
                        .HasColumnType("int")
                        .HasColumnName("id_tramite");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_origen");

                    b.Property<string>("Navegador")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("navegador");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SistemaOperativo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sistema_operativo");

                    b.HasKey("IdCita")
                        .HasName("PK__Citas__6AEC3C092F0BF515");

                    b.HasIndex("IdCiudadano");

                    b.HasIndex("IdSede");

                    b.HasIndex("IdTramite");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.Ciudadano", b =>
                {
                    b.Property<int>("IdCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ciudadano");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCiudadano"));

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasMaxLength(18)
                        .IsUnicode(false)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("curp");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("OrigenRegistro")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("origen_registro");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("primer_apellido");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("segundo_apellido");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCiudadano")
                        .HasName("PK__Ciudadan__676FF54B1A98BECA");

                    b.HasIndex(new[] { "Curp" }, "UQ__Ciudadan__2CDDD194822D2264")
                        .IsUnique();

                    b.ToTable("Ciudadanos");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.ConfiguracionAgenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.HasKey("Id");

                    b.ToTable("Configuracion_Agenda", (string)null);
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.DiasInhabile", b =>
                {
                    b.Property<int>("IdDiaInhabil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_dia_inhabil");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiaInhabil"));

                    b.Property<DateOnly>("FechaBloqueada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_bloqueada");

                    b.Property<int?>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("motivo");

                    b.HasKey("IdDiaInhabil")
                        .HasName("PK__Dias_Inh__2488E88C2B3103CD");

                    b.HasIndex("IdSede");

                    b.ToTable("Dias_Inhabiles", (string)null);
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.HorariosSede", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_horario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<byte>("DiaSemana")
                        .HasColumnType("tinyint")
                        .HasColumnName("dia_semana");

                    b.Property<TimeOnly>("HoraApertura")
                        .HasColumnType("time")
                        .HasColumnName("hora_apertura");

                    b.Property<TimeOnly>("HoraCierre")
                        .HasColumnType("time")
                        .HasColumnName("hora_cierre");

                    b.Property<int>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    b.HasKey("IdHorario")
                        .HasName("PK__Horarios__C5836D69FA1A6428");

                    b.HasIndex("IdSede");

                    b.ToTable("Horarios_Sede", (string)null);
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.RegistroAcceso", b =>
                {
                    b.Property<int>("IdAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_acceso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAcceso"));

                    b.Property<DateTime?>("FechaLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_login");

                    b.Property<DateTime?>("FechaLogout")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_logout");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdAcceso");

                    b.ToTable("Registro_Accesos", (string)null);
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__6ABCB5E0D56A4E16");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.Sede", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSede"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("municipio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdSede")
                        .HasName("PK__Sedes__D693504B010B634E");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.Tramite", b =>
                {
                    b.Property<int>("IdTramite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tramite");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTramite"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("costo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int")
                        .HasColumnName("duracion_minutos");

                    b.Property<DateTime?>("FechaFinPermitida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin_permitida");

                    b.Property<DateTime?>("FechaInicioPermitida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio_permitida");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("LimiteDiarioSede")
                        .HasColumnType("int")
                        .HasColumnName("limite_diario_sede");

                    b.Property<string>("NombreTramite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_tramite");

                    b.Property<string>("Requisitos")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("requisitos");

                    b.HasKey("IdTramite")
                        .HasName("PK__Tramites__DC2729AE6A30BD91");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Tramites");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.UsuariosInterno", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<bool?>("RequiereCambioPassword")
                        .HasColumnType("bit")
                        .HasColumnName("requiere_cambio_password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__4E3E04ADB8D06CD7");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSede");

                    b.HasIndex(new[] { "Username" }, "UQ__Usuarios__F3DBC572531AC299")
                        .IsUnique();

                    b.ToTable("Usuarios_Internos", (string)null);
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.BitacoraAuditorium", b =>
                {
                    b.HasOne("RegistroCivilAPI.Models.UsuariosInterno", "IdUsuarioInternoNavigation")
                        .WithMany("BitacoraAuditoria")
                        .HasForeignKey("IdUsuarioInterno")
                        .IsRequired()
                        .HasConstraintName("FK__Bitacora___id_us__59063A47");

                    b.Navigation("IdUsuarioInternoNavigation");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.Cita", b =>
                {
                    b.HasOne("RegistroCivilAPI.Models.Ciudadano", "IdCiudadanoNavigation")
                        .WithMany("Citas")
                        .HasForeignKey("IdCiudadano")
                        .IsRequired()
                        .HasConstraintName("FK__Citas__id_ciudad__4CA06362");

                    b.HasOne("RegistroCivilAPI.Models.Sede", "IdSedeNavigation")
                        .WithMany("Citas")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK__Citas__id_sede__4E88ABD4");

                    b.HasOne("RegistroCivilAPI.Models.Tramite", "IdTramiteNavigation")
                        .WithMany("Citas")
                        .HasForeignKey("IdTramite")
                        .IsRequired()
                        .HasConstraintName("FK__Citas__id_tramit__4D94879B");

                    b.Navigation("IdCiudadanoNavigation");

                    b.Navigation("IdSedeNavigation");

                    b.Navigation("IdTramiteNavigation");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.DiasInhabile", b =>
                {
                    b.HasOne("RegistroCivilAPI.Models.Sede", "IdSedeNavigation")
                        .WithMany("DiasInhabiles")
                        .HasForeignKey("IdSede")
                        .HasConstraintName("FK__Dias_Inha__id_se__5441852A");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.HorariosSede", b =>
                {
                    b.HasOne("RegistroCivilAPI.Models.Sede", "IdSedeNavigation")
                        .WithMany("HorariosSedes")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK__Horarios___id_se__5165187F");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.Tramite", b =>
                {
                    b.HasOne("RegistroCivilAPI.Models.CategoriasTramite", "IdCategoriaNavigation")
                        .WithMany("Tramites")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK__Tramites__id_cat__44FF419A");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.UsuariosInterno", b =>
                {
                    b.HasOne("RegistroCivilAPI.Models.Role", "IdRolNavigation")
                        .WithMany("UsuariosInternos")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__Usuarios___id_ro__3E52440B");

                    b.HasOne("RegistroCivilAPI.Models.Sede", "IdSedeNavigation")
                        .WithMany("UsuariosInternos")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK__Usuarios___id_se__3F466844");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.CategoriasTramite", b =>
                {
                    b.Navigation("Tramites");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.Ciudadano", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.Role", b =>
                {
                    b.Navigation("UsuariosInternos");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.Sede", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("DiasInhabiles");

                    b.Navigation("HorariosSedes");

                    b.Navigation("UsuariosInternos");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.Tramite", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("RegistroCivilAPI.Models.UsuariosInterno", b =>
                {
                    b.Navigation("BitacoraAuditoria");
                });
#pragma warning restore 612, 618
        }
    }
}
